import Head from "next/head";
import React from "react";
import { Box } from "@chakra-ui/react";

export type LayoutProps = {
  children: React.ReactNode;
};

function Layout({ children }: LayoutProps) {
  const appPadding: number = 4;
  return (
    <>
      <Head>
        <title>Amazing TODO app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box w="100%" p={appPadding}>
        {children}
      </Box>
    </>
  );
}

export default Layout;
