name: Github Action

on: [push]

env:
  CACHE_IMAGE: ghcr.io/gmilon/todo-next
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker
        uses: ./.github/actions/build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
