name: Github Action

on: [push]

env:
  CACHE_IMAGE: ghcr.io/gmilon/todo-next
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker
        uses: ./.github/actions/build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    name: Run Eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run linter
        uses: ./.github/actions/lint
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    needs:
      - test
      - build
      - lint
    steps:
      - name: Deploying to production
        run: 'echo "todo =)"'
